prompt Creating AI Procurement Agents tables

create sequence aipa_purchase_requests_seq start with 1 increment by 1 nocache;

create table aipa_departments (
    department_id number generated by default on null as identity primary key,
    department_code varchar2(30) not null unique,
    department_name varchar2(200) not null,
    cost_center varchar2(30),
    created_by varchar2(255) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_at timestamp with local time zone default systimestamp not null,
    updated_by varchar2(255),
    updated_at timestamp with local time zone
);

create table aipa_employees (
    employee_id number generated by default on null as identity primary key,
    employee_number varchar2(30) not null unique,
    full_name varchar2(200) not null,
    email varchar2(320) not null unique,
    job_title varchar2(120),
    department_id number not null references aipa_departments(department_id),
    approval_limit number(14,2) default 0 not null,
    is_active varchar2(1) default 'Y' not null check (is_active in ('Y','N')),
    created_by varchar2(255) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_at timestamp with local time zone default systimestamp not null,
    updated_by varchar2(255),
    updated_at timestamp with local time zone
);

create table aipa_vendors (
    vendor_id number generated by default on null as identity primary key,
    vendor_name varchar2(200) not null,
    vendor_status varchar2(30) default 'APPROVED' not null,
    risk_level varchar2(10) default 'LOW' not null check (risk_level in ('LOW','MEDIUM','HIGH')),
    tax_identifier varchar2(80),
    created_by varchar2(255) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_at timestamp with local time zone default systimestamp not null,
    updated_by varchar2(255),
    updated_at timestamp with local time zone
);

create table aipa_purchase_requests (
    purchase_request_id number generated by default on null as identity primary key,
    request_number varchar2(30) not null unique,
    requester_id number not null references aipa_employees(employee_id),
    department_id number not null references aipa_departments(department_id),
    vendor_id number references aipa_vendors(vendor_id),
    title varchar2(240) not null,
    business_justification varchar2(4000),
    status varchar2(30) default 'DRAFT' not null
        check (status in ('DRAFT','AI_REVIEWED','SUBMITTED','PENDING_APPROVAL','APPROVED','REJECTED','CHANGES_REQUESTED')),
    risk_level varchar2(10) default 'LOW' not null check (risk_level in ('LOW','MEDIUM','HIGH')),
    requested_date date default trunc(sysdate) not null,
    submitted_at timestamp with local time zone,
    total_amount number(14,2) default 0 not null,
    currency_code varchar2(3) default 'USD' not null,
    created_by varchar2(255) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_at timestamp with local time zone default systimestamp not null,
    updated_by varchar2(255),
    updated_at timestamp with local time zone
);

create table aipa_purchase_request_lines (
    line_id number generated by default on null as identity primary key,
    purchase_request_id number not null references aipa_purchase_requests(purchase_request_id) on delete cascade,
    line_number number not null,
    item_description varchar2(500) not null,
    category varchar2(80) not null,
    quantity number(12,2) default 1 not null,
    unit_price number(14,2) default 0 not null,
    line_amount number(14,2) generated always as (quantity * unit_price) virtual,
    created_by varchar2(255) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_at timestamp with local time zone default systimestamp not null,
    updated_by varchar2(255),
    updated_at timestamp with local time zone,
    constraint aipa_pr_lines_uk unique (purchase_request_id, line_number)
);

create table aipa_procurement_policies (
    policy_id number generated by default on null as identity primary key,
    policy_code varchar2(60) not null unique,
    policy_name varchar2(200) not null,
    severity varchar2(10) not null check (severity in ('LOW','MEDIUM','HIGH')),
    rule_type varchar2(40) not null,
    threshold_amount number(14,2),
    category varchar2(80),
    policy_text varchar2(4000) not null,
    recommended_resolution varchar2(1000),
    is_active varchar2(1) default 'Y' not null check (is_active in ('Y','N')),
    created_by varchar2(255) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_at timestamp with local time zone default systimestamp not null,
    updated_by varchar2(255),
    updated_at timestamp with local time zone
);

create table aipa_approval_rules (
    approval_rule_id number generated by default on null as identity primary key,
    rule_name varchar2(200) not null,
    min_amount number(14,2) default 0 not null,
    max_amount number(14,2),
    risk_level varchar2(10) check (risk_level in ('LOW','MEDIUM','HIGH')),
    department_id number references aipa_departments(department_id),
    approver_id number not null references aipa_employees(employee_id),
    step_order number not null,
    is_active varchar2(1) default 'Y' not null check (is_active in ('Y','N')),
    created_by varchar2(255) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_at timestamp with local time zone default systimestamp not null,
    updated_by varchar2(255),
    updated_at timestamp with local time zone
);

create table aipa_approval_steps (
    approval_step_id number generated by default on null as identity primary key,
    purchase_request_id number not null references aipa_purchase_requests(purchase_request_id) on delete cascade,
    step_order number not null,
    approver_id number not null references aipa_employees(employee_id),
    status varchar2(30) default 'PENDING_APPROVAL' not null
        check (status in ('PENDING_APPROVAL','APPROVED','REJECTED','CHANGES_REQUESTED','SKIPPED')),
    action_comment varchar2(2000),
    acted_at timestamp with local time zone,
    created_by varchar2(255) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_at timestamp with local time zone default systimestamp not null,
    updated_by varchar2(255),
    updated_at timestamp with local time zone,
    constraint aipa_approval_steps_uk unique (purchase_request_id, step_order)
);

create table aipa_agent_runs (
    agent_run_id number generated by default on null as identity primary key,
    purchase_request_id number references aipa_purchase_requests(purchase_request_id),
    agent_static_id varchar2(120) not null,
    status varchar2(20) default 'STARTED' not null check (status in ('STARTED','SUCCEEDED','FAILED','MOCKED')),
    model_name varchar2(120),
    provider_name varchar2(80),
    mode varchar2(20) default 'MOCK' not null check (mode in ('MOCK','LIVE')),
    prompt clob,
    response clob,
    raw_response clob,
    error_message varchar2(4000),
    started_at timestamp with local time zone default systimestamp not null,
    ended_at timestamp with local time zone,
    duration_ms number,
    created_by varchar2(255) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_at timestamp with local time zone default systimestamp not null,
    updated_by varchar2(255),
    updated_at timestamp with local time zone
);

create table aipa_agent_messages (
    agent_message_id number generated by default on null as identity primary key,
    agent_run_id number not null references aipa_agent_runs(agent_run_id) on delete cascade,
    message_role varchar2(30) not null check (message_role in ('SYSTEM','USER','ASSISTANT','TOOL')),
    message_text clob,
    message_json clob check (message_json is json),
    created_by varchar2(255) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_at timestamp with local time zone default systimestamp not null,
    updated_by varchar2(255),
    updated_at timestamp with local time zone
);

create table aipa_agent_tool_calls (
    agent_tool_call_id number generated by default on null as identity primary key,
    agent_run_id number not null references aipa_agent_runs(agent_run_id) on delete cascade,
    tool_name varchar2(120) not null,
    status varchar2(20) default 'STARTED' not null check (status in ('STARTED','SUCCEEDED','FAILED','MOCKED')),
    parameters_json clob check (parameters_json is json),
    result_json clob check (result_json is json),
    error_message varchar2(4000),
    started_at timestamp with local time zone default systimestamp not null,
    ended_at timestamp with local time zone,
    duration_ms number,
    created_by varchar2(255) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_at timestamp with local time zone default systimestamp not null,
    updated_by varchar2(255),
    updated_at timestamp with local time zone
);

create table aipa_agent_recommendations (
    recommendation_id number generated by default on null as identity primary key,
    agent_run_id number not null references aipa_agent_runs(agent_run_id) on delete cascade,
    purchase_request_id number not null references aipa_purchase_requests(purchase_request_id),
    summary varchar2(1000),
    risk_level varchar2(10) check (risk_level in ('LOW','MEDIUM','HIGH')),
    recommended_action varchar2(120),
    explanation clob,
    recommendation_json clob check (recommendation_json is json),
    requires_confirmation varchar2(1) default 'N' not null check (requires_confirmation in ('Y','N')),
    created_by varchar2(255) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_at timestamp with local time zone default systimestamp not null,
    updated_by varchar2(255),
    updated_at timestamp with local time zone
);

create table aipa_app_settings (
    setting_name varchar2(120) primary key,
    setting_value varchar2(4000),
    setting_description varchar2(1000),
    is_secret varchar2(1) default 'N' not null check (is_secret in ('Y','N')),
    created_by varchar2(255) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    created_at timestamp with local time zone default systimestamp not null,
    updated_by varchar2(255),
    updated_at timestamp with local time zone
);

create or replace trigger aipa_pr_lines_biu
    before insert or update on aipa_purchase_request_lines
    for each row
begin
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'), user);
    :new.updated_at := systimestamp;
end;
/

create or replace trigger aipa_pr_lines_aiud
    after insert or update or delete on aipa_purchase_request_lines
declare
begin
    merge into aipa_purchase_requests pr
    using (
        select purchase_request_id, sum(line_amount) total_amount
          from aipa_purchase_request_lines
         group by purchase_request_id
    ) lines
       on (pr.purchase_request_id = lines.purchase_request_id)
     when matched then update set pr.total_amount = nvl(lines.total_amount, 0),
                                  pr.updated_by = coalesce(sys_context('APEX$SESSION','APP_USER'), user),
                                  pr.updated_at = systimestamp;
end;
/

create index aipa_pr_status_ix on aipa_purchase_requests(status);
create index aipa_pr_risk_ix on aipa_purchase_requests(risk_level);
create index aipa_steps_approver_ix on aipa_approval_steps(approver_id, status);
create index aipa_tool_calls_run_ix on aipa_agent_tool_calls(agent_run_id);
